[project]
name = "AI_Powered_Legal_Research_Platform"
version = "0.1.0"
description = "Python Environment"
readme = "README.md"
requires-python = "==3.12.1"
dependencies = [
    "pytest==9.1.1",
    "streamlit==1.63.0",
    "rank-bm25==0.2.2",
    "sentence-transformers==6.0.1",
    "numpy==2.5.3",
    "faiss-cpu==1.15.0",
    "transformers==5.17.0",
    "torch==2.5.1"
]

